SLEX = ..\..\build\OpenSLex.exe

true_test:
	$(SLEX) TRUE_array_test.txt
	$(SLEX) TRUE_directives_test.txt
	$(SLEX) TRUE_float_test.txt
	$(SLEX) TRUE_ifdef_test
	$(SLEX) TRUE_macros_test
	$(SLEX) TRUE_struct_test
	$(SLEX) TRUE_test_struct
	$(SLEX) TRUE_typedef_test

false_test:
	$(SLEX) FALSE_if_test.txt
	$(SLEX) FALSE_prog_1.txt
	$(SLEX) FALSE_prog_2_test.txt
	$(SLEX) FALSE_prog_3.txt
	$(SLEX) FALSE_test_ptr.txt